### ISSUE TITLE
PowerPoint couldn't load the add-in "IguanaTex_v1_60_2.ppam" error message

### ISSUE THREAD

**Issue by Atcold** [Jonathan-LeRoux/IguanaTex#58] opened 2024-02-27 18:59 UTC
Recently, I've been getting the following error when starting up PowerPoint.

> PowerPoint couldn't load the add-in "/Users/atcold/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/IguanaTex_v1_60_2.ppam".

If I `cd` in that location, I find `IguanaTex_v1_60_3.ppam`.
I wonder what is looking for `IguanaTex_v1_60_2.ppam`.

The plugin seems to work just fine, though.

**Comment by Jonathan-LeRoux** [comment] 2024-02-28 15:36
I'm guessing the .ppam file for the previous version was deleted when you upgraded to v1.60.3, but the add-in was not unregistered in PowerPoint.

Do you remember if you upgraded to v1.60.3 manually or using @tsung-ju's brew installation?
The brew installation doesn't unregister previous versions, but it also doesn't delete the ppam file, so it shouldn't create an issue. Could you maybe have deleted it when installing manually?

If you look into Tools > PowerPoint Add-ins..., do you see both versions?
If not, maybe you will need to use AppleScript to fix it. I know next to nothing about AppleScript, but, [based on @tsung-ju's homebrew script](https://github.com/tsung-ju/homebrew-iguanatexmac/blob/master/Casks/iguanatexmac.rb), I'm guessing something like this could work:
```
version '1.60.2'
ppam_name = "IguanaTex_v#{version.gsub('.', '_')}.ppam"
tell application "Microsoft PowerPoint"
  if add ins is not missing value then
    repeat with addIn in (add ins as list)
      if name of addIn = "#{ppam_name}" then
        set loaded of addIn to false
        set auto load of addIn to false
        set registered of addIn to false
      end if
    end repeat
  end if
end tell
```

**Comment by Atcold** [comment] 2024-02-28 19:28
My `brew` updates automatically all its packages, therefore it bumped up IguanaTeX as well.
I see both versions under PowerPoint Add-ins, with the older one disabled.
<img width="375" alt="image" src="https://github.com/Jonathan-LeRoux/IguanaTex/assets/2119355/e790a396-f605-4edb-bc05-36e65ae8eb07">
Still, PowerPoint looks for the missing file.
I guess I can just delete the item in the panel.

**Comment by Atcold** [comment] 2024-02-28 19:29
Confirming that deleting the item gets rid of the error message.

**Comment by Jonathan-LeRoux** [comment] 2024-02-29 18:43
Thanks for the update! It's odd that the `brew` upgrade removed the file without unregistering it. I'm wondering if this could happen because the upgrade happened while PowerPoint was open: I just tried with the machine of a colleague of mine and the same thing happened. Now I need to find someone else on v1.60.2 to try upgrading after closing PowerPoint (is it possible to downgrade a third-party cask to a previous version??).

**Comment by Jonathan-LeRoux** [comment] 2024-03-14 23:41
I did some tests and found that closing PowerPoint did not help`brew` automatically remove the old add-in from the list of add-ins in PowerPoint. I thus improved the upgrade instructions in the README.md of @tsung-ju's [homebrew-iguanatexmac](https://github.com/tsung-ju/homebrew-iguanatexmac) repo, and opened a [PR](https://github.com/tsung-ju/homebrew-iguanatexmac/pull/1). Hopefully, it will be merged soon.

**Closed by Jonathan-LeRoux** 2024-03-14 23:41 UTC

**Comment by tsung-ju** [comment] 2024-03-15 00:39
The Homebrew script was intended to unregister the add-in from PowerPoint. However, it seems PowerPoint change their api so that the add-in's name no longer includes a ".ppam" suffix, which broke the script. This should be easy to fix. I will look into it.

**Comment by Jonathan-LeRoux** [comment] 2024-03-15 01:07
Thanks as always! Feel free to ignore/edit my PR.

**Comment by Atcold** [comment] 2024-06-19 18:21
Thanks to both! 😀
