### ISSUE TITLE
ghostscript error: Unrecoverable error: limitcheck in .putdeviceprops

### ISSUE THREAD

**Issue by klieret** [Jonathan-LeRoux/IguanaTex#29] opened 2022-05-08 09:58 UTC
I run a trivial latex snippet:

```latex
\documentclass{article}
\usepackage{amsmath}
\pagestyle{empty}
\begin{document}

$V_{cb}$


\end{document}
```

but the ghostscript step (cropping) fails. Entering the command that is being run on the command line, I get the error

```
$ '/opt/homebrew/bin/gs' -q -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=IguanaTex_tmp_tmp.pdf -g120780002x83700003 -dFIXEDMEDIA -c "<</PageOffset [-149273994.9 -705563977.9]>>setpagedevice" -f '/private/var/folders/g3/1y2_hl1j16scls01cxqm76s80000gn/T/com.microsoft.Powerpoint/TemporaryItems/IguanaTex_tmp.pdf'
Unrecoverable error: limitcheck in .putdeviceprops
```

This is on Mac Silicon with 

* IguanaTex 1.59
*  gs 9.56.1
* ppt 16.60

**Comment by Jonathan-LeRoux** [comment] 2022-05-09 16:33
I think this is a duplicate of https://github.com/Jonathan-LeRoux/IguanaTex/issues/18. 
I have fixed this in the to-be-released v1.60, for which there is a [beta version available](https://github.com/Jonathan-LeRoux/IguanaTex/files/8343339/IguanaTex_v1_60_0.zip). Could you please give it a try?

**Comment by klieret** [comment] 2022-05-14 20:12
Hi @Jonathan-LeRoux ! Thanks for answering so quickly and sorry for being late with testing. The zip file you sent  contains a `pptm` and I tested opening that. It has the IguanaTex toolbar, but nothing happens when I click the icons (and I've enabled macros). 

However, afterwards I installed the old version again and suddenly it started working (no more error from gs).

I'm actually confused why this is happening, I had tested the previous version multiple times. Or perhaps it's because I had restarted the machine in between or some other unrelated things?

**Closed** 2022-05-14 20:12 UTC

**Comment by Jonathan-LeRoux** [comment] 2022-05-14 20:58
Sorry for the lack of instructions! To get the .ppam, you need to "export" and choose the .ppam extension, then install the add-in as usual.
Indeed, the buttons tend not to work when using the .pptm file. Sometimes they do, sometimes they don't, I think that's an Office bug. But that's only an issue for me as a developer, not for the user who will be using the .ppam anyway.
I'm not sure why this issue would be resolved without the fix I mentioned, unless you changed your locale. But I'm confident it will be resolved after moving to the latest version, so let's close this issue indeed.
