### ISSUE TITLE
[Problem] "Input Code" and "Use templates"  

### ISSUE THREAD

**Issue by yikim0127** [Jonathan-LeRoux/IguanaTex#17] opened 2021-06-11 15:02 UTC
Your codes are very useful,  and a great helper to me! 

Before the problem started, I'm Korean.
I have no ability to check about other languages.
It seems there is a problem to hold "Make Default" 's information.

this is an original form of what I want to hold as a default
![form0](https://user-images.githubusercontent.com/48386990/121700628-1017b500-cb0b-11eb-920c-350252614369.png)
, base on this, and added my inputs:
![form1](https://user-images.githubusercontent.com/48386990/121701564-fd51b000-cb0b-11eb-97d8-3ec8c9b378c5.png)
"Generation" or "ReGenerate" correctly works (It is helpful). 

After I make the 1'st one as "Default Make"

And "New LaTex display" 
![form2](https://user-images.githubusercontent.com/48386990/121705894-13616f80-cb10-11eb-8593-562306846353.png)

I get this form, some final parts of the default form are disappeared.

Please help me

**Comment by Jonathan-LeRoux** [comment] 2021-06-12 15:47
Hi,

Thanks for pointing these issues out. I thought I had fixed this back in v1.42, but apparently I hadn't :)
The problem is that multi-byte strings appear not to be handled well when saving them to the registry, and they get chopped.
A workaround for now is to add as many new lines after `\end{document}` as you have multi-byte characters. I guess somewhere in the pipeline, the length of the string gets counted as the number of characters instead of the number of bytes. It's actually surprising that the string doesn't get mangled instead of chopped.

I now realize that the ["fix" introduced in v1.42](https://github.com/Jonathan-LeRoux/IguanaTex/blob/87f5b079812c75479641f55e15ac2166c94a0016/LatexForm.frm#L1309) had 2 issues:
- it only applied to templates, not the code in the main window
- it didn't actually work, because adding 1 line is not enough; the number of lines to be added depends on the number of multi-byte characters (at least it does now in my current setup; I don't believe I would have let such an issue slip by, but who knows)
The proper fix is probably to use the Windows API function RegSetValueExW (Unicore version) instead of RegSetValueExA (ANSI version). I need to look into this, as it may need quite a lot of changes. [Here is a reference](http://blog.nkadesign.com/2013/10/01/vba-unicode-strings-and-the-windows-api/) that looks relevant.

By the way, if anyone reads this and is getting "?????" instead of the Unicode characters, you probably need to setup the "Language for non-unicode programs" to either a locale that includes these characters, or "Beta: Use Unicode UTF-8 for worldwide language support".

Thanks,
Jonathan

**Comment by Jonathan-LeRoux** [comment] 2022-05-20 22:08
I'm happy to report that this has now been fixed in the [v1.60 release](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.60). Please give it a try!

**Closed by Jonathan-LeRoux** 2022-05-20 22:08 UTC
Labels: bug
